In [13]:
import pandas as pd
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

In [14]:
DATADIR=r'CIFAR-10-images-master\train'

In [15]:
Catagories=["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [16]:
for category in Catagories:
    path=os.path.join(DATADIR,category)
    for img in os.listdir(path):
        img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
        plt.imshow(img_array,cmap="gray")
        plt.show()
        break
    break

In [17]:
dir

<function dir>

In [18]:
print(img_array)

[[201 203 204 ... 205 202 201]
 [211 208 209 ... 209 207 206]
 [213 209 213 ... 213 211 210]
 ...
 [219 213 193 ... 240 238 236]
 [212 217 217 ... 247 244 237]
 [221 221 220 ... 238 241 236]]


In [19]:
img_array.shape

(32, 32)

In [26]:
training_data=[]
IMG_SIZE=50
def create_training_data():
    for category in Catagories:
        path=os.path.join(DATADIR,category)
        class_num=Catagories.index(category)
        for img in os.listdir(path):
            try:   
                img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
                new_array=cv2.resize(img_array,IMG_SIZE)
                training_data.append([new_array,class_num])
            except Exception as e:
                pass
create_training_data()

In [21]:
path

'CIFAR-10-images-master\\train\\airplane'

In [22]:
os.path

<module 'ntpath' from 'F:\\game\\anaconda\\lib\\ntpath.py'>

In [24]:
len(training_data)

0

In [27]:
training_data

[]